### PR TITLE
Make locale files consistent

### PR DESCRIPTION
**Pull request by Scriptim**
See e1aa4a7 and #57 

@radomirbosak Could you test the translations? For some reason, [your suggestion](https://github.com/radomirbosak/duden/pull/64#issuecomment-410019828) with the `LANG` environment variable doesn't work for me if I try it in the local repo or after installing it with `setup.py`. Strangely enough, it works with the installed version of Pypi.

I have adapted the German translations, but some of the Spanish ones still have to be revised.

### CODE REVIEW

**Comment by Scriptim** [comment]
Okay, I managed to test it using `gettext.translation` and it seems to work fine.

One more thing struck me: the description of the `--help` option comes from `argparse` and is therefore not translated.

**Comment by radomirbosak** [comment]
Thanks for filling this PR. I'll review it when I return from vacation (1 week).

**Comment by radomirbosak** [comment]
I squashed your commits and pushed them as 6a54cc357c1fd038cd298e8f284d041cb778f130

**Comment by radomirbosak** [comment]
For the `--help` translation: it would be nice if the phrase was translated, but I don't see it as that much of a problem if it isn't. Feel free to file an issue/PR about it though.

**Comment by Scriptim** [comment]
Why is the PR declared *closed* rather than *merged*?

**Pull request closed without merging**
