### PR TITLE
Add bash and fish shell completion

### LINKED ISSUE #56: Add shell completion
It's useful, you don't have to remember or look up usage information. Ideally, you should be able to press tab to autocomplete or see relevant suggestions.

### PR DESCRIPTION
**Pull request by radomirbosak**
And two Makefile targets to install them

Fixes #56

### CODE REVIEW

**Comment by jorgesumle** [comment]
> can you please check if this shell completion is fine with you?

For me it's not enough. It doesn't distinguish between options that require arguments and options that don't (remember that duden also has the option `--result`). You can see a good example of a completion file in the project ddgr ([Bash completion from ddgr](https://github.com/jarun/ddgr/blob/master/auto-completion/bash/ddgr-completion.bash))

**Comment by radomirbosak** [comment]
How about now? The script now doesn't complete anything after seeing `--result`, for other switches (with optional arguments or no arguments) it autocompletes normally.

**Comment by jorgesumle** [comment]
I looks OK now

**Comment by radomirbosak** [comment]
Great :) I'm merging this then.

**Pull request merged**
